# Generated by Django 3.1.3 on 2020-11-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0002_auto_20201123_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/moto/'),
        ),
    ]
