# Generated by Django 3.1.3 on 2020-11-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0003_motorcycle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='NewApp/static/img/moto/'),
        ),
    ]
