# Generated by Django 3.1.3 on 2020-11-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0004_auto_20201123_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moto/'),
        ),
    ]
