# Generated by Django 3.1.3 on 2020-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0009_auto_20201127_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='newbie',
            field=models.BooleanField(default=False),
        ),
    ]
