# Generated by Django 3.1.3 on 2020-11-30 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('NewApp', '0010_motorcycle_newbie'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLoggedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tele_num', models.IntegerField(default=380, max_length=12)),
                ('delivery', models.CharField(choices=[('Odessa', 'Одесса'), ('Kiev', 'Киев'), ('Dnepr', 'Днепр')], default='Kiev', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tele_num', models.IntegerField(default=380, max_length=12)),
                ('delivery', models.CharField(choices=[('Odessa', 'Одесса'), ('Kiev', 'Киев'), ('Dnepr', 'Днепр')], default='Kiev', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.motorcycle')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='NonLoggedOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.motorcycle')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.nonloggedorder')),
            ],
        ),
    ]
