# Generated by Django 3.1.3 on 2020-11-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0011_nonloggedorder_nonloggedorderitem_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloggedorder',
            name='tele_num',
            field=models.IntegerField(default=380),
        ),
        migrations.AlterField(
            model_name='order',
            name='tele_num',
            field=models.IntegerField(default=380),
        ),
    ]
