# Generated by Django 3.1.3 on 2020-11-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0012_auto_20201130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloggedorderitem',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
