# Generated by Django 3.1.3 on 2020-11-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0013_auto_20201130_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloggedorderitem',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
