# Generated by Django 3.1.3 on 2020-11-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0014_auto_20201130_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloggedorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.motorcycle'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewApp.motorcycle'),
        ),
    ]
