# Generated by Django 3.1.3 on 2020-11-30 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newApp', '0015_auto_20201130_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonloggedorderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.nonloggedorder'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newApp.order'),
        ),
    ]
