# Generated by Django 3.1.3 on 2020-12-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0016_auto_20201130_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
