# Generated by Django 3.1.3 on 2020-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0017_auto_20201202_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
